{
 "title": "dashboard_proyecto_mario",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "GeoMapa",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (geoip_country_code) (count_over_time({job=\"nginx-geoip\"} | json [$__interval]))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Visitantes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({job=\"nginx-geoip\"} | json [$__interval])))"
    }
   ]
  },
  {
   "title": "Peticiones",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({job=\"nginx-geoip\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Promedio Tiempo Respuesta",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "{job=\"nginx-geoip\"} | json | line_format \"{{.request_time}}\""
    }
   ]
  },
  {
   "title": "Tabla Visitantes",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 5 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Solicitudes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(status) (count_over_time({job=\"nginx-geoip\"}|json [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Páginas Solicitadas",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 15 },
   "targets": [
    {
     "expr": "sum by(request) (count_over_time({job=\"nginx-geoip\"}| json [$__interval]))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Tabla Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{job=\"nginx-geoip\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"nginx-geoip\"} |= ``"
    }
   ]
  }
 ]
}